In [2]:
import sys
import yaml
import argparse
import numpy as np
import igraph as ig
import networkx as nx
import matplotlib.pyplot as plt
from qlgates.config import Config
from qlgates.run_dynamics import propagate_state, build_unitary, bell_state
from qlgates.qlgraphs import qldit, cart_qldit, compute_eigen_decomposition
from qlgates.gates import get_Vg, cnot, transform1
from qlgates.helpers import build_local_operators, expectation
from qlgates.cldyn import transverse_field_ising, initial_state_z_up,evolve_times, propagate_state_classical, transverse_ising_trotter
from qlgates.constants import *
from core.contraction import minimal_quotient
from core.graph_generation import generate_quantum_like_bit

In [3]:
print(sys.executable)   # should show your conda env path, not system python

"""Load YAML and merge into Config dataclass."""
with open("../configs/contraction.yaml") as f:
    overrides = yaml.safe_load(f)  # plain dict from YAML

# These are computed in __post_init__, never let YAML set them
overrides.pop("l", None)
overrides.pop("lp", None)

# Create Config instance with merged parameters
cfg = Config(**overrides)

/Users/sahadebadrita/opt/anaconda3/envs/graphs/bin/python


In [4]:
print(cfg)

Config(debug=False, n=32, k=20, d=1, l=5, lp=4, coupling=True, periodic=False, full=False, NQL=2, CartPdt=True, model='transverse', timesteps=100, deltat=0.1, J=-1.0, h=0.2)


In [5]:
#Checking Will's package
qlbit_1p, info_1p = generate_quantum_like_bit(cfg.n,cfg.k,cfg.l)
qlbit_2p, info_2p = generate_quantum_like_bit(cfg.n,cfg.k,cfg.lp)

In [6]:
qlbit_1pmin,info_1pmin = minimal_quotient((qlbit_1p,info_1p))
qlbit_2pmin,info_2pmin = minimal_quotient((qlbit_2p,info_2p))

In [7]:
#Get Cartesian Product of the minimal repn.
min_cartpdt12 = cart_qldit(qlbit_1pmin,qlbit_2pmin)
print(min_cartpdt12.shape)

(4, 4)


In [8]:
e_min_cartpdt12, v_min_cartpdt12 = np.linalg.eigh(min_cartpdt12)
print(e_min_cartpdt12)
print(v_min_cartpdt12)

[31. 39. 41. 49.]
[[ 0.5 -0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5  0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5 -0.5]]


Test single QL-bit states in min rep

In [9]:
e_qlbit1_min, v_qlbit1_min = np.linalg.eigh(qlbit_1pmin)
print(e_qlbit1_min)
print(v_qlbit1_min)

[15. 25.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


Check single QL-bit gates

In [69]:
H = get_Vg('H',theta=None,U=None)
X = get_Vg('x',theta=None,U=None)

Ux = H @ X @ H
print(expectation(v_qlbit1_min,Ux))

print(v_qlbit1_min)
print('Ux @ v_qlbit1_min:')
print(Ux @ v_qlbit1_min)
print('Ux @ qlbit_1pmin @ Ux.T.conj():')
print(Ux @ qlbit_1pmin @ Ux.T.conj())

[0. 0.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
Ux @ v_qlbit1_min:
[[-0.70710678+0.j  0.70710678+0.j]
 [-0.70710678+0.j -0.70710678+0.j]]
Ux @ qlbit_1pmin @ Ux.T.conj():
[[20.+0.j -5.+0.j]
 [-5.+0.j 20.+0.j]]


In [10]:
H = get_Vg('H',theta=None,U=None)
Z = get_Vg('z',theta=None,U=None)

Uz = H @ Z @ H
print(expectation(v_qlbit1_min,Uz))
print(v_qlbit1_min)
print('Uz @ v_qlbit1_min:')
print(Uz @ v_qlbit1_min)
print('Uz @ qlbit_1pmin @ Uz.T.conj():')
print(Uz @ qlbit_1pmin @ Uz.T.conj())

[-1.  1.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
Uz @ v_qlbit1_min:
[[ 0.70710678+0.j  0.70710678+0.j]
 [-0.70710678+0.j  0.70710678+0.j]]
Uz @ qlbit_1pmin @ Uz.T.conj():
[[20.+0.j  5.+0.j]
 [ 5.+0.j 20.+0.j]]


In [ ]:
H = get_Vg('H',theta=None,U=None)
RX = get_Vg('Rx',theta=1.57,U=None)

URx = H @ RX @ H
print(URx @ v_qlbit1_min)
print(URx @ qlbit_1pmin @ URx.T.conj())

[[-0.50019904+0.49980088j  0.50019904-0.49980088j]
 [ 0.50019904+0.49980088j  0.50019904+0.49980088j]]
[[2.00000000e+01+0.j         3.98163355e-03-4.99999841j]
 [3.98163355e-03+4.99999841j 2.00000000e+01+0.j        ]]


Basis change for 2 ql-bits

In [ ]:
e_qlbit2_min, v_qlbit2_min = np.linalg.eigh(qlbit_2pmin)
print(e_qlbit2_min)
print(v_qlbit2_min)

[16. 24.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
e_min_cartpdt12, v_min_cartpdt12 = np.linalg.eigh(min_cartpdt12)

UCB2 = np.kron(H, H)

print(e_min_cartpdt12)
print(v_min_cartpdt12)
print(np.real(UCB2 @ v_min_cartpdt12))

[31. 39. 41. 49.]
[[ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]]
[[-3.33066907e-16  1.33226763e-15  2.38697950e-15 -1.00000000e+00]
 [-3.33066907e-16 -1.00000000e+00 -8.10462808e-15 -1.27675648e-15]
 [ 5.55111512e-16 -7.88258347e-15  1.00000000e+00  2.38697950e-15]
 [ 1.00000000e+00 -2.77555756e-16 -6.38378239e-16 -5.55111512e-17]]


In [ ]:
CNOT = np.array([
    [1, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0]
])

In [40]:
UCNOT = UCB2 @ CNOT @ UCB2
print((UCNOT @ v_min_cartpdt12).real)


[[ 0.5 -0.5  0.5 -0.5]
 [-0.5  0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5 -0.5 -0.5]]


In [ ]:
print((UCNOT @ v_min_cartpdt12).real - v_min_cartpdt12.real)

Check CNOT gate

In [13]:
UCNOT = cnot(1, theta=None, U=None)
print(UCNOT)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]


Check the Hadamard gate

In [16]:
Hadamard = transform1('H', 1, theta=None, U=None)
print(Hadamard)

[[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]


In [19]:
cfg.n = 1
psi_bell_phi_plus = bell_state(cfg, v_min_cartpdt12[:,-1], kind="phi_plus")
print(psi_bell_phi_plus)

[-7.07106781e-01+0.j -6.10622664e-16+0.j -6.66133815e-16+0.j
 -7.07106781e-01+0.j]


In [20]:
psi_bell_phi_minus = bell_state(cfg, v_min_cartpdt12[:,-1], kind="phi_minus")
print(psi_bell_phi_minus)

[-6.66133815e-16+0.j -7.07106781e-01+0.j -7.07106781e-01+0.j
 -6.10622664e-16+0.j]


In [21]:
psi_bell_psi_plus = bell_state(cfg, v_min_cartpdt12[:,-1], kind="psi_plus")
print(psi_bell_psi_plus)

[-7.07106781e-01+0.j -6.10622664e-16+0.j  6.66133815e-16+0.j
  7.07106781e-01+0.j]


In [22]:
psi_bell_psi_minus = bell_state(cfg, v_min_cartpdt12[:,-1], kind="psi_minus")
print(psi_bell_psi_minus)

[ 6.66133815e-16+0.j  7.07106781e-01+0.j -7.07106781e-01+0.j
 -6.10622664e-16+0.j]


Trotter circuits for Transverse Ising Hamiltonian

In [14]:
cfg.n = 1
#psi0 = v_min_cartpdt12[:,-1]
psi0 = np.kron(v_qlbit1_min[:,-1],v_qlbit1_min[:,-1])
psit = propagate_state(cfg,psi0,build_unitary)

In [15]:
print(psi0)

[0.5 0.5 0.5 0.5]


In [ ]:
cfg.NQL = 10
cfg.n = 1
times = np.arange(0, cfg.timesteps * cfg.deltat, cfg.deltat)
psi0 = v_qlbit1_min[:,-1]  # ground state of the first QL-bit
for i in range(cfg.NQL-1):
    psi0 = np.kron(psi0,v_qlbit1_min[:,-1])  # ground state of the product system
psi0 = psi0 / np.linalg.norm(psi0)  # normalize the state vector
#psi0 = initial_state_z_up(cfg.NQL)
for j in range(cfg.NQL):
    mz = build_local_operators(Uz,I2,cfg.NQL)

M_eq_exact = []  # Store equilibrium values for each site
ratios = []  # Store ratios for each site

for cfg.h in [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0]:
#for cfg.h in [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]:
#for h in [0.0]:
    #Create Hamiltonian and compute eigenvalues/eigenvectors
    #H = transverse_field_ising(cfg.NQL, cfg.h, cfg.J)
    #print(psi0.shape, H.shape)

    psit = propagate_state(cfg, psi0, build_unitary)
    print(psit.shape)

    expectation_mz_exact = np.empty((psit.shape[1], cfg.NQL+2))  # +2 for time steps and mean expectation
    for j in range(len(mz)):
        expectation_mz_exact[:,j] = expectation(psit, mz[j])
    expectation_mz_exact[:,-1] = np.arange(cfg.timesteps)  # Add time steps as the last column
    expectation_mz_exact[:,-2] = np.mean(expectation_mz_exact[:,:-2], axis=1)  # Add mean expectation values as the second-to-last column
    M_eq_exact.append(np.mean(np.abs(expectation_mz_exact[int(0.0*cfg.timesteps):,-2])))  # Mean of the absolute values of the mean expectation values in the last 20% of time steps
    ratios.append(abs(cfg.h/cfg.J))  # Ratio of the equilibrium value at this h to the equilibrium value at the smallest h

print(M_eq_exact)
print(ratios)


(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
(1024, 100)
[0.9999999999998481, 0.9950056807022075, 0.9725150202319257, 0.9243933549924721, 0.8489667355663475, 0.7485370261532199, 0.6298758310647508, 0.4958609900804045, 0.34420593977087094, 0.1849237265358769, 0.10081366788739295, 0.11241694548806866, 0.09701507182934493, 0.09227687020945899, 0.09475120142326884, 0.09122610545488825, 0.09203634246131825, 0.08950427409066926, 0.09041374557220205, 0.08748550086696762, 0.08963636449991626]
[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]


In [24]:
plt.plot(ratios, M_eq_exact, marker='o')
plt.xlabel('h/|J|')
plt.ylabel(r'$\bar{M}_{z}$')
plt.title(r'$\bar{M}_{z}$ vs h/|J|')
plt.savefig('contraction_NQL10_2_TFIM.png')
plt.close()
#plt.show()

In [37]:
print(mz)

[array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+0.j, -1.+0.j]]), array([[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j,  0.+0.j, -0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j, -0.+0.j,  0.+0.j, -1.+0.j]])]
